In [9]:
import pandas as pd
import numpy as np
import matplotlib
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')
from sklearn.metrics import confusion_matrix

In [10]:
train = pd.read_csv("train_ready_for_model_loan.csv")
train.head()

Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0  LP001002             5849                0.0       126.0             360.0   
1  LP001003             4583             1508.0       128.0             360.0   
2  LP001005             3000                0.0        66.0             360.0   
3  LP001006             2583             2358.0       120.0             360.0   
4  LP001008             6000                0.0       141.0             360.0   

   Credit_History  Loan_Status  Gender_Female  Gender_Male  Married_No  \
0             1.0            1              0            1           1   
1             1.0            0              0            1           0   
2             1.0            1              0            1           0   
3             1.0            1              0            1           0   
4             1.0            1              0            1           1   

          ...           Dependents_1  Dependents_2  Dependents_3+  \
0         ...                      0             0              0   
1         ...                      1             0              0   
2         ...                      0             0              0   
3         ...                      0             0              0   
4         ...                      0             0              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                   1                       0                 1   
1                   1                       0                 1   
2                   1                       0                 0   
3                   0                       1                 1   
4                   1                       0                 1   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                  0                    0                        0   
1                  0                    1                        0   
2                  1                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    0  
2                    1  
3                    1  
4                    1  

[5 rows x 22 columns]

In [11]:
test = pd.read_csv("test_ready_for_model_loan.csv")
test.head()

Loan_ID  ApplicantIncome  CoapplicantIncome  LoanAmount  Loan_Amount_Term  \
0  LP001015             5720                0.0       110.0             360.0   
1  LP001022             3076             1500.0       126.0             360.0   
2  LP001031             5000             1800.0       208.0             360.0   
3  LP001035             2340             2546.0       100.0             360.0   
4  LP001051             3276                0.0        78.0             360.0   

   Credit_History  Gender_Female  Gender_Male  Married_No  Married_Yes  \
0             1.0              0            1           0            1   
1             1.0              0            1           0            1   
2             1.0              0            1           0            1   
3             1.0              0            1           0            1   
4             1.0              0            1           1            0   

          ...           Dependents_1  Dependents_2  Dependents_3+  \
0         ...                      0             0              0   
1         ...                      1             0              0   
2         ...                      0             1              0   
3         ...                      0             1              0   
4         ...                      0             0              0   

   Education_Graduate  Education_Not Graduate  Self_Employed_No  \
0                   1                       0                 1   
1                   1                       0                 1   
2                   1                       0                 1   
3                   1                       0                 1   
4                   0                       1                 1   

   Self_Employed_Yes  Property_Area_Rural  Property_Area_Semiurban  \
0                  0                    0                        0   
1                  0                    0                        0   
2                  0                    0                        0   
3                  0                    0                        0   
4                  0                    0                        0   

   Property_Area_Urban  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1  

[5 rows x 21 columns]

In [169]:
#Define target and ID columns:
target = 'Loan_Status'
IDcol = ['Loan_ID']


def modelfit(alg,dtrain,dtest,predictors,target,IDcol,filename):
    from sklearn.metrics import confusion_matrix
    #fit the algorithm on the data
    alg.fit(dtrain[predictors],dtrain[target])
    
    #predict training set
    dtrain_predictions=alg.predict(dtrain[predictors])
    
    #Error Metrics
    confusion_matrix = confusion_matrix(dtrain[target], dtrain_predictions)
    print(confusion_matrix)
    
    #Accuracy
    print('Accuracy of classifier on train set: {:.2f}'.format(alg.score(dtrain[predictors],dtrain[target])))
    
    #predict test set
    dtest[target]=alg.predict(dtest[predictors])
       
    #Export Submission File:
    IDcol.append(target)

    #submission=pd.DataFrame({x:dtest.Loan_Status[x] for x in IDcol})
    submission=pd.DataFrame(dtest['Loan_ID'])
    submission['Loan_Status']=dtest[target]
    submission['Loan_Status']=submission.Loan_Status.replace({1:'Y',0:'N'})
    submission.to_csv(filename,index=False)
    

In [170]:
#1.Logistic Regression
from sklearn.linear_model import LogisticRegression
predictors=[x for x in train.columns if x not in [target]+IDcol]
print('Predictors:',predictors)
alg1=LogisticRegression()
modelfit(alg1,train,test,predictors,target,IDcol,'res2.csv')
#logreg = LogisticRegression()
#logreg.fit(X,Y)

Predictors: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
[[ 84 108]
 [  7 415]]
Accuracy of classifier on train set: 0.81


In [173]:
#2.KNN
from sklearn.neighbors import KNeighborsClassifier
#k = 5
predictors=[x for x in train.columns if x not in [target]+IDcol]
print('Predictors:',predictors)
for i in range(1,20):
    alg1=KNeighborsClassifier(n_neighbors = i)
    modelfit(alg1,train,test,predictors,target,IDcol,'res_KNN.csv')

Predictors: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
[[192   0]
 [  0 422]]
Accuracy of classifier on train set: 1.00
[[192   0]
 [124 298]]
Accuracy of classifier on train set: 0.80
[[ 99  93]
 [ 43 379]]
Accuracy of classifier on train set: 0.78
[[122  70]
 [ 85 337]]
Accuracy of classifier on train set: 0.75
[[ 64 128]
 [ 38 384]]
Accuracy of classifier on train set: 0.73
[[ 93  99]
 [ 72 350]]
Accuracy of classifier on train set: 0.72
[[ 50 142]
 [ 26 396]]
Accuracy of classifier on train set: 0.73
[[ 63 129]
 [ 56 366]]
Accuracy of classifier on train set: 0.70
[[ 37 155]
 [ 21 401]]
Accuracy of classifier on train set: 0.71
[[ 54 138]
 [ 37 385]]

In [161]:
#3.Decision Tree
from sklearn.tree import DecisionTreeClassifier
#k = 5
predictors=[x for x in train.columns if x not in [target]+IDcol]
print('Predictors:',predictors)
alg1=DecisionTreeClassifier(max_depth=10, min_samples_leaf=60)
modelfit(alg1,train,test,predictors,target,IDcol,'res_DesTree.csv')

Predictors: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
[[ 82 110]
 [  7 415]]
Accuracy of classifier on test set: 0.81


In [134]:
#4.Random Forest
from sklearn.ensemble import RandomForestClassifier
predictors=[x for x in train.columns if x not in [target]+IDcol]
print('Predictors:',predictors)
alg1=RandomForestClassifier(n_estimators=200,max_depth=15,min_samples_leaf=30)
modelfit(alg1,train,test,predictors,target,IDcol,'res_RanFst.csv')

Predictors: ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term', 'Credit_History', 'Gender_Female', 'Gender_Male', 'Married_No', 'Married_Yes', 'Dependents_0', 'Dependents_1', 'Dependents_2', 'Dependents_3+', 'Education_Graduate', 'Education_Not Graduate', 'Self_Employed_No', 'Self_Employed_Yes', 'Property_Area_Rural', 'Property_Area_Semiurban', 'Property_Area_Urban']
[[ 75 117]
 [  7 415]]


In [135]:
#5.AdaBoost
from sklearn.ensemble import AdaBoostClassifier
predictors = [x for x in train.columns if x not in [target]+IDcol]
# print predictors
alg1 = AdaBoostClassifier(n_estimators=200)
modelfit(alg1, train, test, predictors, target, IDcol, 'res_Adabst.csv')

[[123  69]
 [ 11 411]]


In [149]:
#6.XGBoost
from xgboost import XGBClassifier
predictors = [x for x in train.columns if x not in [target]+IDcol]
alg1 = XGBClassifier(max_depth=10, n_estimators=100, learning_rate=0.05)
modelfit(alg1, train, test, predictors, target, IDcol, 'res_xgbst.csv')

[[180  12]
 [  5 417]]


In [187]:
#7.Stacking
from sklearn import model_selection
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from mlxtend.classifier import StackingClassifier
import numpy as np

clf1=KNeighborsClassifier(n_neighbors=1)
clf2=RandomForestClassifier(random_state=1)
clf3=DecisionTreeClassifier()
lr=LogisticRegression()
alg1=StackingClassifier(classifiers=[clf1,clf2,clf3],meta_classifier=lr)
modelfit(alg1, train, test, predictors, target, IDcol, 'res_stack.csv')

[[192   0]
 [  0 422]]
Accuracy of classifier on train set: 1.00


In [186]:
StackingClassifier?
for clf,label in zip([clf1,clf2,clf3,sclf],
                    ['KNN', 
                       'Random Forest', 
                       'Decision Tree',
                       'Stacking Regressor']):
    #Error Metrics
    confusion_matrix = confusion_matrix(train[target], sclf.)
    print(confusion_matrix)
    
    #Accuracy
    print('Accuracy of classifier on train set: {:.2f}'.format(lr.score(train[predictors],train[target])))